version: "3.3"
services:

db-service:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - /home/ict/data/db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: your_database
    command: mysqld --sql_mode=""
    restart: on-failure
