version: "3"

services:
  db-service:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - snipesql-vol:/var/lib/mysql
    environment:
        MYSQL_USER: root
        MYSQL_DATABASE: snipe
        MYSQL_PASSWORD: dbjaya
        MYSQL_ROOT_PASSWORD: dbjaya
        TZ: Asia/Jakarta
    command: mysqld --sql_mode=""
  snipe-it:
    image: snipe/snipe-it
    ports:
      - "80:80"
    volumes:
      - /home/ict/data/config:/config
    environment:
        PUID: 1000
        PGID: 1000
        DB_CONNECTION: mysql
        DB_HOST: db-service
        DB_DATABASE: snipe
        DB_USERNAME: root
        DB_PASSWORD: dbjaya
        APP_KEY: base64:5U/KPKw1GN/Rz0fWYO/4FsSOqjmjvDAQzMCqwcAqstc=
        APP_URL: http://192.168.100.132
    restart: on-failure
    depends_on:
      - db-service

volumes:
  snipesql-vol:
